spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000/"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
      routes:
        - id: kbe_application_service
          uri: http://localhost:8081/
          predicates:
            - Path=/api/gifs/**

        - id: kbe_calculation_service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/calculator/**
