spring:
  cloud:
    gateway:
      routes:
        - id: kbe_application_service
          uri: http://localhost:8081/
          predicates:
            - Path=/gifs/**

        - id: kbe_calculation_service
          uri: http://localhost:8082/
          predicates:
            - Path=/calculator/**
